### ISSUE TITLE
Swedish characters

### ISSUE THREAD

**Issue by dvwallin** [practicalswift/openemacs#5]
There's a problem with Swedish characters. I suspect most non-english characters fails. When pressing Å or Ä  och Ö all I get is ???.

Would it be possible to add utf8 support to openemacs? Or to solve this issue in any other fashion?

I really like the editor but I couldn't use it without the support of Swedish chars.

**Comment by practicalswift** [comment]
Hi @dvwallin!

Unicode code point `å` (`U+00E5`: `LATIN SMALL LETTER A WITH RING ABOVE`) is represented as the UTF-8 byte string`\xc3\xa5`.

Running `openemacs foo.txt`, entering `test å` and then pressing `^X^S` will write `test \xc3\xa5\n` (the bytes as-is plus a newline) to the file `foo.txt`. Running `cat foo.txt` in an UTF-8 capable terminal will hence render `test å` as expected. So far so good.

Unfortunately, `test å` will be rendered as `test ??` within `openemacs`. The question marks represent the two non-ASCII-characters `\xc3\xa5` (the UTF-8 byte string for code point `å`).

This is due to `openemacs` having no concept of encodings, so `\xc3\xa5` is interpreted as two unprintable characters instead of the UTF-8 representation of `å`.

Giving `openemacs` proper Unicode support will probably require adding external dependencies and bump the LOC considerably.

One idea I've thought about is adding support for rending Unicode code points for all printable characters in the Latin-1 Supplement block.

**Comment by felipebueno** [comment]
I wish I could help you with that but I don't know much about encodings and C programming yet =/

https://github.com/practicalswift/openemacs/issues/3#issuecomment-270014294

**Comment by practicalswift** [comment]
I'm closing this issue. I've decided `openemacs` will stick with printing ASCII characters only to keep the LOC count down.
